//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTubeWindows {
    using System;
    
    
    /// <summary>
    ///   A strongly typed resource class, used to look up localized strings, etc.
    /// </summary>
    // This class was generated by the StronglyTypedResourceBuilder class
    // through a tool like ResGen or Visual Studio.
    // To add or remove members, edit the .ResX file and then rerun ResGen
    // (with /str as a command option) or rebuild the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YouTubeWindows.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the CurrentUICulture property of the current thread for
        ///   all resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a resource similar to /**
        /// * Creates a Proxy used to intercept and log activity
        /// * @param {Object|Function} targetObject The target object or function
        /// * @param {String} path The current object path being tracked for log output
        /// * @returns {Proxy} The proxied object
        /// */
        ///function createBridgeProxy(targetObject, path = &apos;mockObject&apos;) {
        ///
        ///    // Wrapped logging helper
        ///    const log = (message) =&gt; {
        ///        if (window.StarboardBridge &amp;&amp; typeof window.StarboardBridge.ConsoleWriteLine === &apos;function&apos;) {
        ///            window.StarboardBridge.ConsoleWriteLine(message);
        ///        } else {
        ///            // If StarboardBridge is not injected yet, fall back to console. [string truncated]"; localized string.
        /// </summary>
        public static string InitJs {
            get {
                return ResourceManager.GetString("InitJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a string similar to YouTube Leanback for Windows &lt;--%PROGRAM_VERSION%--&gt;
        ///By TGSAN
        ///
        ///Windows Cobalt on EBWebView2
        ///Microsoft Edge (Chromium) Runtime
        ///Version: &lt;--%WEBVIEW_VERSION%--&gt;
        ///
        ///YouTube
        ///
        ///YouTube is a subsidiary of Google localized string.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!--
        ///  Copyright 2020 Google LLC. All Rights Reserved.
        ///
        ///  Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        ///  you may not use this file except in compliance with the License.
        ///  You may obtain a copy of the License at
        ///
        ///      http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///  Unless required by applicable law or agreed to in writing, software
        ///  distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        ///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express o [truncated string]"; localized string.
        /// </summary>
        public static string youtube_splash_screen {
            get {
                return ResourceManager.GetString("youtube_splash_screen", resourceCulture);
            }
        }
    }
}
